#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

# APP="$1"; IMAGE=$(get_app_image_name $APP); CACHE_DIR="$DOKKU_ROOT/$APP/cache"

# APP="$1"; 
# $IMAGE_SOURCE_TYPE="$2";
# IMAGE_TAG="$3"; PROC_TYPE="$4"; CONTAINER_INDEX="$5"; 
# IMAGE=$(get_app_image_name $APP $IMAGE_TAG)

echo 'dokku-test Running test script at docker-args-process-deploy...'

PLUGIN_DIR=$(dirname $0)
PLUGIN_EXEC_CMD="plugn trigger"

echo 'dokku-test Running test script at docker-args-process-deploy...' 1>&2
echo ' --label mylabel=cool '
#STDIN=$(cat)
#echo -n "$@"
